# Generated by Django 5.1.4 on 2025-01-07 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Пікір')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Қолданушы пікірі',
                'verbose_name_plural': 'Қолданушылар пікірлері',
            },
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Жалпы ұпай пайызы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to='main.subject', verbose_name='Пән')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Қолданушының курсы',
                'verbose_name_plural': 'Қолданушының курстары',
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Балл')),
                ('completed', models.BooleanField(default=False, verbose_name='Аяқталды')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Жіберілген уақыт')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to='main.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Қолданушының тесті',
                'verbose_name_plural': 'Қолданушылардың тесттері',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл')),
                ('answers', models.ManyToManyField(to='main.option', verbose_name='Жауаптар')),
                ('user_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='progress.usertest', verbose_name='Қолданушы тесті')),
            ],
            options={
                'verbose_name': 'Қолданушының жауабы',
                'verbose_name_plural': 'Қолданушылардың жауаптары',
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Сабақтың баллы')),
                ('completed', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Орындалған уақыты')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='main.lesson', verbose_name='Сабақ')),
                ('user_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='progress.usersubject', verbose_name='Қолданушының курсы')),
            ],
            options={
                'verbose_name': 'Қолданушының сабағы',
                'verbose_name_plural': 'Қолданушылардың сабақтары',
                'unique_together': {('user_subject', 'lesson')},
            },
        ),
    ]
