# Generated by Django 5.1.4 on 2025-01-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubject',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Орындалды'),
        ),
    ]
