# Generated by Django 5.1.4 on 2024-12-30 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_userhomework_user_lesson_alter_homework_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubject',
            options={'verbose_name': 'Қолданушының курсы', 'verbose_name_plural': 'Қолданушының курстары'},
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='user_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='progress.usersubject', verbose_name='Қолданушының курсы'),
        ),
    ]
