# Generated by Django 5.1.4 on 2025-01-09 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_framecontent_url'),
        ('progress', '0003_alter_usersubject_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='submitted_at',
        ),
        migrations.CreateModel(
            name='UseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.FileField(upload_to='main/subject/user/homeworks/', verbose_name='Тапсырма')),
                ('grade', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Пікір')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='main.task', verbose_name='Тапсырма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
                ('user_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='progress.userlesson', verbose_name='Қолданушының сабағы')),
            ],
            options={
                'verbose_name': 'Қолданушының тапсырмасы',
                'verbose_name_plural': 'Қолданушылардың тапсырмалары',
            },
        ),
    ]
