# Generated by Django 5.1.4 on 2024-12-30 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_question_option_test_question_test'),
        ('progress', '0003_alter_usersubject_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Балл')),
                ('completed', models.BooleanField(default=False, verbose_name='Аяқталды')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Жіберілген уақыт')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to='main.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Қолданушының тесті',
                'verbose_name_plural': 'Қолданушылардың тесттері',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл')),
                ('answers', models.ManyToManyField(to='main.option', verbose_name='Жауаптар')),
                ('user_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='progress.usertest', verbose_name='Қолданушы тесті')),
            ],
            options={
                'verbose_name': 'Қолданушының жауабы',
                'verbose_name_plural': 'Қолданушылардың жауаптары',
            },
        ),
    ]
