# Generated by Django 5.1.4 on 2025-01-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_usertest_user_lesson_alter_usetask_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
