# Generated by Django 5.1.4 on 2025-01-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_useranswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Ашық сабақ'),
        ),
    ]
