# Generated by Django 5.1.4 on 2025-01-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0008_userlesson_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usetask',
            name='grade',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Балл'),
        ),
    ]
