# Generated by Django 5.1.4 on 2025-04-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_alter_usetask_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubject',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Орындалған уақыты'),
        ),
    ]
