# Generated by Django 5.1.4 on 2024-12-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('default', 'Қолданушы типін таңдау'), ('student', 'Білім алушы'), ('teacher', 'Оқытушы')], default='default', max_length=128, verbose_name='Қолданушы түрі'),
        ),
    ]
