# Generated by Django 5.1.4 on 2025-01-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Білім алушы'), ('teacher', 'Оқытушы')], default='student', max_length=128, verbose_name='Пайдаланушы түрі'),
        ),
    ]
