# Generated by Django 5.1.4 on 2025-01-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Тақырыбы')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Мәтіні')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контенттер',
            },
        ),
    ]
