# Generated by Django 5.1.4 on 2024-12-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Сурет шаршы форматта болуы керек. Мысалы: (512x512)px', null=True, upload_to='accounts/avatars/', verbose_name='Пайдаланушы суреті'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('default', 'Пайдаланушы типін таңдау'), ('student', 'Білім алушы'), ('teacher', 'Оқытушы')], default='default', max_length=128, verbose_name='Пайдаланушы түрі'),
        ),
    ]
