# Generated by Django 5.1.4 on 2025-01-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/content/images/', verbose_name='Сурет'),
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Реттілік'),
        ),
        migrations.AddField(
            model_name='content',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='accounts/content/videos/', verbose_name='Видео'),
        ),
    ]
