# Generated by Django 5.1.4 on 2025-01-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_content_image_content_order_content_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('order',), 'verbose_name': 'Контент', 'verbose_name_plural': 'Контенттер'},
        ),
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
    ]
