# Generated by Django 5.1.4 on 2025-04-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_content_options_remove_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Тобы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Мамандық'),
        ),
    ]
