# Generated by Django 5.1.4 on 2025-01-08 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_subject_options_remove_lesson_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('created_at',), 'verbose_name': 'Пән', 'verbose_name_plural': 'Пәндер'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='main.subject', verbose_name='Пән'),
        ),
    ]
