# Generated by Django 5.1.4 on 2025-01-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_subject_options_alter_chapter_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL iframe сілтеме')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_contents', to='main.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Фрейм контент',
                'verbose_name_plural': 'Фрейм контенттер',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тапсырма сұрақтары')),
                ('total_score', models.PositiveIntegerField(default=100, verbose_name='Жалпы балл')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Тапсырма',
                'verbose_name_plural': 'Тапсырмалар',
            },
        ),
    ]
