# Generated by Django 5.1.4 on 2025-01-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_textcontent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framecontent',
            name='url',
            field=models.TextField(verbose_name='URL iframe сілтеме'),
        ),
    ]
