# Generated by Django 5.1.4 on 2025-01-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_framecontent_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Сұрақ мәтіні'),
        ),
    ]
