# Generated by Django 5.1.4 on 2025-01-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Балл'),
        ),
    ]
