# Generated by Django 5.1.4 on 2025-01-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_option_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Сұрақ мәтіні'),
        ),
    ]
