# Generated by Django 5.1.4 on 2025-01-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_test_description_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Жауап мәтіні'),
        ),
    ]
