# Generated by Django 5.1.4 on 2024-12-30 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userolympic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userolympic',
            name='olympic',
        ),
        migrations.RemoveField(
            model_name='userolympic',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('-created_at',), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курстар'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='main.subject', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.subject', verbose_name='Курс'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Olympic',
        ),
        migrations.DeleteModel(
            name='UserOlympic',
        ),
    ]
