# Generated by Django 5.1.4 on 2025-04-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_option_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cert',
            field=models.FileField(blank=True, null=True, upload_to='main/subject/certs', verbose_name='Сертификат'),
        ),
    ]
