# Generated by Django 5.1.4 on 2024-12-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_module_course_remove_userolympic_olympic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('theory', 'Теориялық сабақ'), ('practice', 'Практикалық сабақ')], max_length=255, verbose_name='Сабақтың түрі'),
        ),
    ]
